// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'localization_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

LocalizationAttributes _$LocalizationAttributesFromJson(
  Map<String, dynamic> json,
) => LocalizationAttributes(
  appTitle: json['appTitle'] as String,
  companyName: json['companyName'] as String,
  region: json['region'] as String,
  footerText: json['footerText'] as String,
  navHome: json['navHome'] as String,
  navServices: json['navServices'] as String,
  navProcess: json['navProcess'] as String,
  navGallery: json['navGallery'] as String,
  navContacts: json['navContacts'] as String,
  heroBadge: json['heroBadge'] as String,
  heroTitle: json['heroTitle'] as String,
  heroDescription: json['heroDescription'] as String,
  heroButtonCalculate: json['heroButtonCalculate'] as String,
  heroButtonConsultation: json['heroButtonConsultation'] as String,
  heroPriceFrom: json['heroPriceFrom'] as String,
  heroPriceDescription: json['heroPriceDescription'] as String,
  statYears: json['statYears'] as String,
  statClients: json['statClients'] as String,
  statSupport: json['statSupport'] as String,
  aboutTitle: json['aboutTitle'] as String,
  aboutSubtitle: json['aboutSubtitle'] as String,
  aboutDescription: json['aboutDescription'] as String,
  featureGuarantee: json['featureGuarantee'] as String,
  featureMasters: json['featureMasters'] as String,
  featureSchedule: json['featureSchedule'] as String,
  featureQuality: json['featureQuality'] as String,
  servicesTitle: json['servicesTitle'] as String,
  servicesSubtitle: json['servicesSubtitle'] as String,
  serviceInstallation: json['serviceInstallation'] as String,
  serviceInstallationDesc: json['serviceInstallationDesc'] as String,
  serviceMaintenance: json['serviceMaintenance'] as String,
  serviceMaintenanceDesc: json['serviceMaintenanceDesc'] as String,
  serviceRepair: json['serviceRepair'] as String,
  serviceRepairDesc: json['serviceRepairDesc'] as String,
  serviceRefill: json['serviceRefill'] as String,
  serviceRefillDesc: json['serviceRefillDesc'] as String,
  serviceDemount: json['serviceDemount'] as String,
  serviceDemountDesc: json['serviceDemountDesc'] as String,
  serviceConsultation: json['serviceConsultation'] as String,
  serviceConsultationDesc: json['serviceConsultationDesc'] as String,
  priceListTitle: json['priceListTitle'] as String,
  priceListSubtitle: json['priceListSubtitle'] as String,
  priceButton: json['priceButton'] as String,
  priceInstallStandard: json['priceInstallStandard'] as String,
  priceInstallEconomy: json['priceInstallEconomy'] as String,
  priceInstallComfort: json['priceInstallComfort'] as String,
  priceInstallMulti: json['priceInstallMulti'] as String,
  priceDemount: json['priceDemount'] as String,
  priceRefill: json['priceRefill'] as String,
  priceCleaning: json['priceCleaning'] as String,
  galleryTitle: json['galleryTitle'] as String,
  gallerySubtitle: json['gallerySubtitle'] as String,
  galleryAll: json['galleryAll'] as String,
  galleryInstallation: json['galleryInstallation'] as String,
  galleryMaintenance: json['galleryMaintenance'] as String,
  galleryRepair: json['galleryRepair'] as String,
  galleryStatsTitle: json['galleryStatsTitle'] as String,
  processTitle: json['processTitle'] as String,
  processSubtitle: json['processSubtitle'] as String,
  processStepsTitle: json['processStepsTitle'] as String,
  processStep1Title: json['processStep1Title'] as String,
  processStep1Desc: json['processStep1Desc'] as String,
  processStep2Title: json['processStep2Title'] as String,
  processStep2Desc: json['processStep2Desc'] as String,
  processStep3Title: json['processStep3Title'] as String,
  processStep3Desc: json['processStep3Desc'] as String,
  processStep4Title: json['processStep4Title'] as String,
  processStep4Desc: json['processStep4Desc'] as String,
  processStep5Title: json['processStep5Title'] as String,
  processStep5Desc: json['processStep5Desc'] as String,
  contactsTitle: json['contactsTitle'] as String,
  contactsSubtitle: json['contactsSubtitle'] as String,
  contactsMapTitle: json['contactsMapTitle'] as String,
  contactsMapSubtitle: json['contactsMapSubtitle'] as String,
  contactsFormTitle: json['contactsFormTitle'] as String,
  contactsFormSubtitle: json['contactsFormSubtitle'] as String,
  contactsFormName: json['contactsFormName'] as String,
  contactsFormPhone: json['contactsFormPhone'] as String,
  contactsFormEmail: json['contactsFormEmail'] as String,
  contactsFormService: json['contactsFormService'] as String,
  contactsFormMessage: json['contactsFormMessage'] as String,
  contactsFormSubmit: json['contactsFormSubmit'] as String,
  contactsFormSuccess: json['contactsFormSuccess'] as String,
  contactsFormNameError: json['contactsFormNameError'] as String,
  contactsFormPhoneError: json['contactsFormPhoneError'] as String,
  ctaTitle: json['ctaTitle'] as String,
  ctaDescription: json['ctaDescription'] as String,
  ctaButtonOrder: json['ctaButtonOrder'] as String,
  ctaButtonAllServices: json['ctaButtonAllServices'] as String,
  error404: json['error404'] as String,
);

Map<String, dynamic> _$LocalizationAttributesToJson(
  LocalizationAttributes instance,
) => <String, dynamic>{
  'appTitle': instance.appTitle,
  'companyName': instance.companyName,
  'region': instance.region,
  'footerText': instance.footerText,
  'navHome': instance.navHome,
  'navServices': instance.navServices,
  'navProcess': instance.navProcess,
  'navGallery': instance.navGallery,
  'navContacts': instance.navContacts,
  'heroBadge': instance.heroBadge,
  'heroTitle': instance.heroTitle,
  'heroDescription': instance.heroDescription,
  'heroButtonCalculate': instance.heroButtonCalculate,
  'heroButtonConsultation': instance.heroButtonConsultation,
  'heroPriceFrom': instance.heroPriceFrom,
  'heroPriceDescription': instance.heroPriceDescription,
  'statYears': instance.statYears,
  'statClients': instance.statClients,
  'statSupport': instance.statSupport,
  'aboutTitle': instance.aboutTitle,
  'aboutSubtitle': instance.aboutSubtitle,
  'aboutDescription': instance.aboutDescription,
  'featureGuarantee': instance.featureGuarantee,
  'featureMasters': instance.featureMasters,
  'featureSchedule': instance.featureSchedule,
  'featureQuality': instance.featureQuality,
  'servicesTitle': instance.servicesTitle,
  'servicesSubtitle': instance.servicesSubtitle,
  'serviceInstallation': instance.serviceInstallation,
  'serviceInstallationDesc': instance.serviceInstallationDesc,
  'serviceMaintenance': instance.serviceMaintenance,
  'serviceMaintenanceDesc': instance.serviceMaintenanceDesc,
  'serviceRepair': instance.serviceRepair,
  'serviceRepairDesc': instance.serviceRepairDesc,
  'serviceRefill': instance.serviceRefill,
  'serviceRefillDesc': instance.serviceRefillDesc,
  'serviceDemount': instance.serviceDemount,
  'serviceDemountDesc': instance.serviceDemountDesc,
  'serviceConsultation': instance.serviceConsultation,
  'serviceConsultationDesc': instance.serviceConsultationDesc,
  'priceListTitle': instance.priceListTitle,
  'priceListSubtitle': instance.priceListSubtitle,
  'priceButton': instance.priceButton,
  'priceInstallStandard': instance.priceInstallStandard,
  'priceInstallEconomy': instance.priceInstallEconomy,
  'priceInstallComfort': instance.priceInstallComfort,
  'priceInstallMulti': instance.priceInstallMulti,
  'priceDemount': instance.priceDemount,
  'priceRefill': instance.priceRefill,
  'priceCleaning': instance.priceCleaning,
  'galleryTitle': instance.galleryTitle,
  'gallerySubtitle': instance.gallerySubtitle,
  'galleryAll': instance.galleryAll,
  'galleryInstallation': instance.galleryInstallation,
  'galleryMaintenance': instance.galleryMaintenance,
  'galleryRepair': instance.galleryRepair,
  'galleryStatsTitle': instance.galleryStatsTitle,
  'processTitle': instance.processTitle,
  'processSubtitle': instance.processSubtitle,
  'processStepsTitle': instance.processStepsTitle,
  'processStep1Title': instance.processStep1Title,
  'processStep1Desc': instance.processStep1Desc,
  'processStep2Title': instance.processStep2Title,
  'processStep2Desc': instance.processStep2Desc,
  'processStep3Title': instance.processStep3Title,
  'processStep3Desc': instance.processStep3Desc,
  'processStep4Title': instance.processStep4Title,
  'processStep4Desc': instance.processStep4Desc,
  'processStep5Title': instance.processStep5Title,
  'processStep5Desc': instance.processStep5Desc,
  'contactsTitle': instance.contactsTitle,
  'contactsSubtitle': instance.contactsSubtitle,
  'contactsMapTitle': instance.contactsMapTitle,
  'contactsMapSubtitle': instance.contactsMapSubtitle,
  'contactsFormTitle': instance.contactsFormTitle,
  'contactsFormSubtitle': instance.contactsFormSubtitle,
  'contactsFormName': instance.contactsFormName,
  'contactsFormPhone': instance.contactsFormPhone,
  'contactsFormEmail': instance.contactsFormEmail,
  'contactsFormService': instance.contactsFormService,
  'contactsFormMessage': instance.contactsFormMessage,
  'contactsFormSubmit': instance.contactsFormSubmit,
  'contactsFormSuccess': instance.contactsFormSuccess,
  'contactsFormNameError': instance.contactsFormNameError,
  'contactsFormPhoneError': instance.contactsFormPhoneError,
  'ctaTitle': instance.ctaTitle,
  'ctaDescription': instance.ctaDescription,
  'ctaButtonOrder': instance.ctaButtonOrder,
  'ctaButtonAllServices': instance.ctaButtonAllServices,
  'error404': instance.error404,
};
